# Exemplo: Execuções com múltiplas métricas
----------------------------

Este exemplo mostra como avaliar um pipeline do experionml com múltiplas métricas.

Importe o conjunto de dados de câncer de mama de [sklearn.datasets](https://scikit-learn.org/stable/datasets/index.html#wine-dataset). Este é um conjunto de dados pequeno e fácil de treinar cujo objetivo é prever se uma paciente tem câncer de mama ou não.

## Carregar os dados

In [1]:
# Import packages
import pandas as pd
from experionml import ExperionMLRegressor

In [2]:
# Carregue os dados
X = pd.read_csv("./datasets/abalone.csv")

# Let's have a look
X.head()

,Sex,Length,Diameter,Height,Whole weight,Shucked weight,Viscera weight,Shell weight,Rings
0,M,0.455,0.365,0.095,0.5140,0.2245,0.1010,0.150,15
1,M,0.350,0.265,0.090,0.2255,0.0995,0.0485,0.070,7
2,F,0.530,0.420,0.135,0.6770,0.2565,0.1415,0.210,9
3,M,0.440,0.365,0.125,0.5160,0.2155,0.1140,0.155,10
4,I,0.330,0.255,0.080,0.2050,0.0895,0.0395,0.055,7

## Executar o pipeline

In [3]:
experionml = ExperionMLRegressor(X, n_jobs=1, verbose=2, random_state=1)

<< ================== ExperionML ================== >>

Configuração ==================== >>
Tarefa do algoritmo: Regression.

Estatísticas do conjunto de dados ==================== >>
Formato: (4177, 9)
Tamanho do conjunto de train: 3342
Tamanho do conjunto de test: 835
-------------------------------------
Memória: 300.87 kB
Escalonado: False
Atributos categóricos: 1 (12.5%)
Valores atípicos: 189 (0.6%)

In [4]:
experionml.encode()

Ajustando Encoder...
Codificando colunas categóricas...
 --> Aplicando OneHot-encoding à variável Sex. Ela contém 3 classes.

In [5]:
# Em cada etapa da BO, ambas as métricas são calculadas,
# mas apenas a primeira é usada para otimização!
experionml.run(
    models=["lsvm", "hGBM"],
    metric=("r2", "rmse"),
    n_trials=10,
    n_bootstrap=6,
)

Training ========================= >>
Models: lSVM, hGBM
Metric: r2, rmse


Running hyperparameter tuning for LinearSVM...
| trial |                    loss |       C |    dual |      r2 | best_r2 |    rmse | best_rmse | time_trial | time_ht |    state |
| ----- | ----------------------- | ------- | ------- | ------- | ------- | ------- | --------- | ---------- | ------- | -------- |
| 0     | squared_epsilon_insen.. |   0.001 |    True |  0.2887 |  0.2887 | -2.6528 |   -2.6528 |     0.068s |  0.068s | COMPLETE |
| 1     | squared_epsilon_insen.. |  0.0534 |   False |  0.4507 |  0.4507 | -2.3314 |   -2.3314 |     0.061s |  0.129s | COMPLETE |

| 2     | squared_epsilon_insen.. |  0.0105 |    True |   0.451 |   0.451 | -2.3307 |   -2.3307 |     0.063s |  0.192s | COMPLETE |

| 3     |     epsilon_insensitive |  0.6215 |    True |  0.4266 |   0.451 | -2.3818 |   -2.3307 |     0.075s |  0.267s | COMPLETE |
| 4     | squared_epsilon_insen.. |  0.0369 |   False |  0.4509 |   0.451 | -2.3308 |   -2.3307 |     0.059s |  0.326s | COMPLETE |
| 5     |     epsilon_insensitive |  0.0016 |    True | -1.5995 |   0.451 | -5.0716 |   -2.3307 |     0.059s |  0.385s | COMPLETE |

| 6     | squared_epsilon_insen.. | 61.5811 |   False |  0.4499 |   0.451 |  -2.333 |   -2.3307 |     0.060s |  0.445s | COMPLETE |

| 7     | squared_epsilon_insen.. |  14.898 |   False |  0.4499 |   0.451 |  -2.333 |   -2.3307 |     0.060s |  0.505s | COMPLETE |
| 8     |     epsilon_insensitive |  0.0252 |    True |  0.3798 |   0.451 | -2.4772 |   -2.3307 |     0.059s |  0.564s | COMPLETE |
| 9     | squared_epsilon_insen.. |  0.0294 |    True |  0.4512 |  0.4512 | -2.3302 |   -2.3302 |     0.066s |  0.630s | COMPLETE |
Hyperparameter tuning ---------------------------
Best trial --> 9
Best parameters:
 --> loss: squared_epsilon_insensitive
 --> C: 0.0294
 --> dual: True
Best evaluation --> r2: 0.4512   rmse: -2.3302
Time elapsed: 0.630s

Fit ---------------------------------------------

Train evaluation --> r2: 0.4587   rmse: -2.3806
Test evaluation --> r2: 0.4586   rmse: -2.3365
Time elapsed: 0.188s

Bootstrap ---------------------------------------
Evaluation --> r2: 0.458 ± 0.0014   rmse: -2.3377 ± 0.0031
Time elapsed: 0.259s
-------------------------------------------------
Time: 1.077s


Running hyperparameter tuning for HistGradientBoosting...
| trial |      loss | quantile | learning_rate | max_iter | max_leaf_nodes | max_depth | min_samples_leaf | l2_regularization |      r2 | best_r2 |    rmse | best_rmse | time_trial | time_ht |    state |
| ----- | --------- | -------- | ------------- | -------- | -------------- | --------- | ---------------- | ----------------- | ------- | ------- | ------- | --------- | ---------- | ------- | -------- |

| 0     | absolut.. |      0.1 |        0.0236 |      180 |             26 |        12 |               11 |               0.0 |  0.5373 |  0.5373 | -2.1398 |   -2.1398 |     0.761s |  0.761s | COMPLETE |
| 1     |     gamma |      0.5 |         0.242 |      160 |             38 |         3 |               20 |               0.0 |   0.556 |   0.556 | -2.0959 |   -2.0959 |     0.181s |  0.942s | COMPLETE |

| 2     |  quantile |      0.4 |        0.2448 |      210 |             12 |         3 |               25 |               0.3 |  0.4906 |   0.556 |  -2.245 |   -2.0959 |     0.603s |  1.544s | COMPLETE |

| 3     |  quantile |      0.6 |         0.017 |      480 |             28 |        16 |               13 |               0.1 |  0.5535 |   0.556 | -2.1018 |   -2.0959 |     2.704s |  4.249s | COMPLETE |

| 4     | squared.. |      1.0 |        0.2649 |       70 |             10 |        10 |               28 |               0.8 |  0.5403 |   0.556 | -2.1327 |   -2.0959 |     0.443s |  4.691s | COMPLETE |

| 5     | squared.. |      0.1 |        0.0283 |      360 |             32 |         9 |               11 |               0.5 |  0.5466 |   0.556 |  -2.118 |   -2.0959 |     0.850s |  5.541s | COMPLETE |

| 6     |  quantile |      0.4 |        0.1264 |      380 |             37 |        12 |               29 |               1.0 |  0.4977 |   0.556 | -2.2292 |   -2.0959 |     2.484s |  8.025s | COMPLETE |

| 7     |     gamma |      0.6 |         0.678 |      330 |             25 |         6 |               12 |               0.8 |  0.3783 |   0.556 | -2.4802 |   -2.0959 |     0.564s |  8.589s | COMPLETE |

| 8     | absolut.. |      0.9 |        0.0831 |      280 |             42 |        16 |               10 |               1.0 |  0.5285 |   0.556 |   -2.16 |   -2.0959 |     2.706s | 11.295s | COMPLETE |

| 9     | absolut.. |      0.6 |        0.0373 |      300 |             40 |        13 |               17 |               0.8 |  0.5381 |   0.556 | -2.1378 |   -2.0959 |     1.536s | 12.830s | COMPLETE |
Hyperparameter tuning ---------------------------
Best trial --> 1
Best parameters:
 --> loss: gamma
 --> quantile: 0.5
 --> learning_rate: 0.242
 --> max_iter: 160
 --> max_leaf_nodes: 38
 --> max_depth: 3
 --> min_samples_leaf: 20
 --> l2_regularization: 0.0

Best evaluation --> r2: 0.556   rmse: -2.0959
Time elapsed: 12.830s
Fit ---------------------------------------------

Train evaluation --> r2: 0.7182   rmse: -1.7178
Test evaluation --> r2: 0.5427   rmse: -2.1473
Time elapsed: 0.190s

Bootstrap ---------------------------------------
Evaluation --> r2: 0.5241 ± 0.022   rmse: -2.19 ± 0.0504
Time elapsed: 1.017s

-------------------------------------------------
Time: 14.038s


Resultados finais ==================== >>
Tempo total: 16.315s
-------------------------------------

LinearSVM            --> r2: 0.458 ± 0.0014   rmse: -2.3377 ± 0.0031

HistGradientBoosting --> r2: 0.5241 ± 0.022   rmse: -2.19 ± 0.0504 ~ !

In [6]:
# Verifique a robustez do pipeline usando validação cruzada
experionml.winner.cross_validate()

Applying cross-validation...

## Analisar os resultados

In [7]:
# As colunas no dataframe de resultados contêm uma para cada métrica
experionml.results.data[["r2_ht", "r2_train", "r2_test", "rmse_ht", "rmse_train", "rmse_test"]]

         r2_ht  r2_train  r2_test   rmse_ht  rmse_train  rmse_test
lSVM  0.451203    0.4580   0.4565 -2.330239     -2.3823    -2.3411
hGBM  0.556021    0.7182   0.5427 -2.095926     -1.7178    -2.1473

In [8]:
# Alguns gráficos permitem escolher a métrica que queremos mostrar
with experionml.canvas():
    experionml.plot_trials(metric="r2", title="Hyperparameter tuning performance for R2")
    experionml.plot_trials(metric="rmse", title="Hyperparameter tuning performance for RMSE")

In [9]:
experionml.plot_results(metric="r2")